In [2]:
import pandas as pd

In [3]:
df_filtered=pd.read_csv("book_filtered_rating.csv")
df_user=pd.read_csv("book_user.csv")
df_info=pd.read_csv("book_info.csv")

In [4]:
df_filtered.shape

(2456, 4)

In [5]:
df_unfilter=pd.read_csv("book_rating.csv")

In [6]:
df_unfilter.shape

(1149780, 4)

In [7]:
df_filtered.head()

   User-ID        ISBN  Rating  book_id
0        2  0195153448     0.0     8968
1        7   034542252     0.0     8969
2        8  0002005018     2.5     8970
3        8  0060973129     0.0     8971
4        8  0374157065     0.0     8972

In [8]:
df_unfilter.head()

   User-ID        ISBN  Rating  book_id
0   276725  034545104X     0.0        1
1   276726  0155061224     2.5        2
2   276727  0446520802     0.0        3
3   276729  052165615X     1.5        4
4   276729  0521795028     3.0        5

SyntaxError: invalid syntax (1219266065.py, line 1)