In [1]:
import pandas as pd
import numpy as np

In [2]:
df_book = pd.read_csv("../data/raw/book/Books.csv", sep=";")
df_rating = pd.read_csv("../data/raw/book/Ratings.csv", sep=";")
df_user = pd.read_csv("../data/raw/book/Users.csv", sep=";")

C:\Users\aditya.kaushal\AppData\Local\Temp\ipykernel_5156\3541953899.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_user = pd.read_csv("../data/raw/book/Users.csv", sep=";")

#

# Books

In [3]:
df_book.head()

,ISBN,Title,Author,Year,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton & Company

In [4]:
print('Book data nulls:-\n',df_book.info())
print()
print('Rating data nulls:-\n',df_rating.info())
print()
print('Users data nulls:-\n',df_user.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271379 entries, 0 to 271378
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ISBN       271379 non-null  object
 1   Title      271379 non-null  object
 2   Author     271377 non-null  object
 3   Year       271379 non-null  int64
 4   Publisher  271377 non-null  object
dtypes: int64(1), object(4)
memory usage: 10.4+ MB
Book data nulls:-
 None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   User-ID  1149780 non-null  int64
 1   ISBN     1149780 non-null  object
 2   Rating   1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB
Rating data nulls:-
 None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278859 entries, 0 to 278858
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   User-ID  278859 non-null  object
 1   Age      168627 non-null  object
dtypes: object(2)
memory usage: 4.3+ MB
Users data nulls:-
 None

In [5]:
print('Book data nulls:-\n',df_book.isnull().sum())
print()
print('Rating data nulls:-\n',df_rating.isnull().sum())
print()
print('Users data nulls:-\n',df_user.isnull().sum())

Book data nulls:-
 ISBN         0
Title        0
Author       2
Year         0
Publisher    2
dtype: int64

Rating data nulls:-
 User-ID    0
ISBN       0
Rating     0
dtype: int64

Users data nulls:-
 User-ID         0
Age        110232
dtype: int64

In [6]:
df_book.dropna(inplace=True)

In [7]:
# Check for total number of duplicate rows
duplicates_book = df_book.duplicated().sum()
print(f"Duplicate rows: {duplicates_book}")
duplicates_rating = df_user.duplicated().sum()
print(f"Duplicate rows: {duplicates_rating}")
duplicates_user = df_rating.duplicated().sum()
print(f"Duplicate rows: {duplicates_user}")

Duplicate rows: 1
Duplicate rows: 0
Duplicate rows: 0

In [8]:
# Drop duplicate rows permanently
df_book.drop_duplicates(inplace=True)

# This removes the 1 duplicate row from df_book in-place.

In [10]:
df_rating.head()

   User-ID        ISBN  Rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [11]:
df_user.head()

  User-ID  Age
0       1  NaN
1       2   18
2       3  NaN
3       4   17
4       5  NaN

In [12]:
df_book.head()

,ISBN,Title,Author,Year,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton & Company