In [1]:
import pandas as pd
import numpy as np

In [2]:
# Define the column names based on the documentation
movie_columns = [
    "movie_id", "title", "release_date", "video_release_date", "IMDb_URL",
    "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy",
    "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror",
    "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"
]
ratings_columns = ["user_id", "item_id", "rating", "timestamp"]
user_columns = ["user_id", "age", "gender", "occupation", "zip_code"]



# Read the file and apply column names

In [3]:
df_rating = pd.read_csv("../data/raw/movie/u.data",sep='\t', encoding='latin-1', header=None, names=ratings_columns)
df_movie = pd.read_csv("../data/raw/movie/u.item", sep='|', encoding='latin-1', header=None, names=movie_columns)
df_user = pd.read_csv("../data/raw/movie/u.user",sep='|', encoding='latin-1', header=None, names=user_columns)

In [8]:
print('Movie data nulls:-\n',df_movie.info())
print()
print('Rating data nulls:-\n',df_rating.info())
print()
print('Users data nulls:-\n',df_user.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1679 entries, 0 to 1681
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      1679 non-null   int64
 1   title         1679 non-null   object
 2   release_date  1679 non-null   object
 3   IMDb_URL      1679 non-null   object
 4   unknown       1679 non-null   int64
 5   Action        1679 non-null   int64
 6   Adventure     1679 non-null   int64
 7   Animation     1679 non-null   int64
 8   Children's    1679 non-null   int64
 9   Comedy        1679 non-null   int64
 10  Crime         1679 non-null   int64
 11  Documentary   1679 non-null   int64
 12  Drama         1679 non-null   int64
 13  Fantasy       1679 non-null   int64
 14  Film-Noir     1679 non-null   int64
 15  Horror        1679 non-null   int64
 16  Musical       1679 non-null   int64
 17  Mystery       1679 non-null   int64
 18  Romance       1679 non-null   int64
 19  Sci-Fi        1679 non-null   int64
 20  Thriller      1679 non-null   int64
 21  War           1679 non-null   int64
 22  Western       1679 non-null   int64
dtypes: int64(20), object(3)
memory usage: 314.8+ KB
Movie data nulls:-
 None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    100000 non-null  int64
 1   item_id    100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB
Rating data nulls:-
 None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB
Users data nulls:-
 None

In [6]:
df_movie.drop(['video_release_date'], axis=1, inplace=True)

In [7]:
df_movie.dropna(inplace=True)

In [26]:
df_movie.head()

Empty DataFrame
Columns: [movie_id, title, release_date, video_release_date, IMDb_URL, unknown, Action, Adventure, Animation, Children's, Comedy, Crime, Documentary, Drama, Fantasy, Film-Noir, Horror, Musical, Mystery, Romance, Sci-Fi, Thriller, War, Western]
Index: []

[0 rows x 24 columns]

In [22]:
df_user.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [23]:
df_rating.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596